name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger blog publish
      uses: fjogeleit/http-request-action@v1.15.5
      with:
        url: https://api.github.com/repos/infojunkie/blog/dispatches
        customHeaders: '{ "Authorization": "Bearer ${{ secrets.TOKEN }}" }'
        data: '{ "event_type": "Profile" }'
